language: objective-c

before_script:
  - bin/ci/travis/instruments-auth.sh

script:
  - bundle install
  - make framework
  - make frank
  - bundle exec bin/test/xctest.rb
  - bundle exec bin/test/run-ios-simulator-smoke-tests.rb --tags @travis

notifications:
  email:
    recipients:
      - joshuajmoody@gmail.com
      - karl.krukow@xamarin.com
      - chris.fuentes@xamarin.com
    on_success: change
    on_failure: always
