language: objective-c

before_script:
  - gem install xcpretty

script:
  - make clean
  - make frank
  - scripts/ci/travis/run-chou-tests.rb
  - scripts/ci/travis/test-make-without-xcpretty.rb

rvm:
  - 2.1.1

notifications:
  email:
    on_success: change
    on_failure: always
