language: objective-c

before_script:
  - gem install xcpretty

script:
  - make clean
  - make framework
  - make frank
  - make dylib
  - make all
  - scripts/ci/travis/run-chou-tests.rb

rvm:
  - 2.1.1

notifications:
  email:
    on_success: change
    on_failure: always
